name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      build-dir: "dist"
      prepare-script: >-
        cp package.json LICENSE README.md dist/ &&
        cd dist &&
        tmp=$(mktemp) &&
        jq --arg version "$GITHUB_REF_NAME" '
          .version = $version |
          .main = "index.js" |
          .types = "index.d.ts"
        ' package.json > "$tmp" &&
        mv "$tmp" package.json
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
